#file: noinspection SpellCheckingInspection
name: coinplus
description: Coinplus Wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Regular dependencies are listed under dependencies:—these are packages that
# anyone using your package will also need.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  dio: ^5.1.2
  sembast: ^3.4.5
  get_it: ^7.2.0
  json_annotation: ^4.8.1
  mobx: ^2.2.0
  flutter_mobx: ^2.1.1
  intl: ^0.18.0
  auto_route: ^7.8.4
  easy_localization: ^3.0.2
  url_launcher: ^6.1.11
  flutter_hooks: ^0.20.3
  styled_text: ^8.1.0
  gap: ^3.0.0
  flutter_scale_tap: ^1.0.5
  lottie: ^2.4.0
  qr_code_scanner: ^1.0.1
  nfc_manager: ^3.2.0
  uni_links: ^0.5.1
  mobile_scanner: ^3.4.1
  flip_card: ^0.7.0
  local_auth: ^2.1.6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0
  animated_segmented_tab_control: ^1.1.0
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.0.1
  text_link: ^1.0.0
  flutter_lints: ^3.0.0
  shake_animation_widget: ^3.0.4
  flutter_branch_sdk: ^6.9.0
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  bs58: ^1.0.2
  elliptic: ^0.3.10
  ecdsa: ^0.1.0
  hashlib: ^1.12.0
  amplitude_flutter: ^3.13.0
  pin_code_fields: ^8.0.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.19.0
  dart_jsonwebtoken: ^2.12.0
  cloud_functions: ^4.5.1
  wolt_modal_sheet: ^0.1.4
  app_settings: ^5.1.1
  flutter_web_browser: ^0.17.1
  nxp_originality_verifier: ^0.0.6
  gaimon: ^1.2.1
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  cloud_firestore: ^4.13.3
  cloud_firestore_odm: ^1.0.0-dev.78
  ramp_flutter: ^3.0.0
  action_slider: ^0.7.0
  did_change_authlocal: ^0.0.6
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  dio_interceptor_plus: ^0.0.2
  sensors_plus: ^4.0.2
  bitcoin_flutter:
    git:
      url: https://github.com/Coinplus/coinplus_bitcoin_flutter.git


dev_dependencies:
  # Provides API to test Flutter applications that run on real devices and emulators.
  flutter_driver:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  json_serializable: ^6.6.1
  mobx_codegen: ^2.2.0
  collection: ^1.17.1
  freezed: ^2.3.2
  theme_tailor: ^2.0.0
  retrofit_generator: ^8.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/app_icon.png'

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80
  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    # Optional
    enabled: true
    # Optional
    outputs:
      # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false
      # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: dot-delimiter
      class_name: Assets
    exclude: ['assets/flags/*.png', 'assets/translations/*.json']
  fonts:
    # Optional
    enabled: true
    # Optional
    outputs:
      class_name: FontFamily
  colors:
    # Optional
    enabled: true
    # Optional
    inputs:
      - assets/colors/colors.xml
    # Optional
    outputs:
      class_name: AppColors

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/icons/
    - assets/images/
    - assets/colors/
    - assets/images/bar/
    - assets/images/card/
    - assets/lottie_animations/
    - assets/lottie_animations/animated_logo.json
    - assets/translations/en-US.json


  fonts:
    - family: RedHatLight
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
          weight: 400
    - family: RedHatSemiBold
      fonts:
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 600
    - family: RedHatBold
      fonts:
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 800

    - family: RedHatMedium
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 400

    - family: LexendThin
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
