name: coinplus
description: Crypto Wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ">=3.0.0 <4.0.0"

# Regular dependencies are listed under dependencies:—these are packages that
# anyone using your package will also need.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  dio: ^5.1.2
  sembast: ^3.4.5
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  intl: ^0.18.0
  auto_route: ^7.3.2
  easy_localization: ^3.0.2
  url_launcher: ^6.1.11
  flutter_hooks: ^0.19.0
  gap: ^3.0.0
  flutter_scale_tap: ^1.0.5
  lottie: ^2.4.0
  qr_code_scanner: ^1.0.1
  nfc_manager: ^3.2.0
  uni_links: ^0.5.1
  mobile_scanner: ^3.4.1
  flip_card: ^0.7.0
  emerge_alert_dialog: ^0.0.3
  local_auth: ^2.1.6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0
  animated_segmented_tab_control: ^1.1.0
  toast: ^0.3.0
  flutter_secure_storage: ^8.0.0
  retrofit: ^4.0.1
  text_link: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_bloc: ^8.0.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shake_animation_widget: ^3.0.4
  pin_lock: ^0.1.0
  flutter_branch_sdk: ^6.8.0
  email_validator: ^2.1.17
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  bs58: ^1.0.2
  flutter_bitcoin: ^1.0.1



dev_dependencies:
  # Provides API to test Flutter applications that run on real devices and emulators.
  flutter_driver:
    sdk: flutter

  # AutoRoute is a declartive routing solution, where everything
  # needed for navigation is automatically generated for you.
  auto_route_generator: ^7.1.1

  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.6.1

  # Code generator for MobX that adds support for annotating your code with
  # @observable, @computed, @action and also creating Store classes.
  mobx_codegen: ^2.2.0
  collection: ^1.17.1

  # Code generation for immutable classes that has a simple
  # syntax/API without compromising on the features.
  freezed: ^2.3.2
  dart_code_metrics: ^5.7.2
  theme_tailor: ^2.0.0
  retrofit_generator: ^7.0.8
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80
  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    # Optional
    enabled: true
    # Optional
    outputs:
      # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false
      # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: dot-delimiter
      class_name: Assets
    exclude: [ 'assets/flags/*.png', 'assets/translations/*.json',]
  fonts:
    # Optional
    enabled: true
    # Optional
    outputs:
      class_name: FontFamily
  colors:
    # Optional
    enabled: true
    # Optional
    inputs:
      - assets/colors/colors.xml
    # Optional
    outputs:
      class_name: AppColors

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/icons/
    - assets/images/
    - assets/colors/
    - assets/animated_logo/nfcanimation.json
    - assets/animated_logo/qr_animation.json
    - assets/animated_logo/address_validation_success.json
    - assets/animated_logo/loading_animation.json
    - assets/translations/en-US.json

  fonts:
    - family: RedHatLight
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
          weight: 400
    - family: RedHatSemiBold
      fonts:
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 600
    - family: RedHatBold
      fonts:
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 800

    - family: RedHatMedium
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 400

    - family: LexendThin
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
