final rampRegions = <String>[
  'Aland Islands',
  'Albania',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Australia',
  'Armenia',
  'Austria',
  'Belgium',
  'Belize',
  'Bermuda',
  'Bhutan',
  'Bonaire, St. Estatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Canada',
  'Cape Verde',
  'Chad',
  'Chile',
  'Christmas Island',
  'Cocos Islands',
  'Colombia',
  'Comoros',
  'Congo, Republic of',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'El Salvador',
  'Equatorial Guinea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Federal States of Micronesia',
  'Finland',
  'France',
  'French Guyana',
  'French Polynesia',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jersey',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Lao PDR',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mayotte',
  'Mexico',
  'Moldova, Republic of',
  'Monaco',
  'Montenegro',
  'Mozambique',
  'Nauru',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Réunion',
  'Romania',
  'Rwanda',
  'Saint Barthélemy',
  'Saint Helena, Ascension & Tristan Da Cunha',
  'Saint Lucia',
  'Saint Martin (France)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and Grenadines',
  'San Marino',
  'Sao Tome and Principe',
  'Serbia',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Netherlands)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vatican City',
  'Wallis and Futuna',
  'Zambia',
];

final rampUsUnavailableStates = <String>[
  'Alabama',
  'Alaska',
  'Florida',
  'Hawaii',
  'Kentucky',
  'Louisiana',
  'Nevada',
  'New Jersey',
  'New Mexico',
  'New York',
  'Ohio',
  'Oregon',
  'Vermont',
  'Washington',
];
